// How each project is previewed. Declarative and keyed by **host**, never by position
// in `content.json`: reordering the list must not change what a given site renders as,
// which is exactly what an index-keyed table would do.
//
// All six are screenshots (`public/previews/<host>.jpg`, regenerated by
// `scripts/capture-previews.ts`). Two of them always were — `creativamedialab.com`
// answers `X-Frame-Options: DENY` and `telecentro.com.ar` sits behind a WAF — and the
// other four moved here for the budget of spec 17: four live cross-origin iframes pull
// 40-50 third-party requests into the page, which cost `/en` Performance 0.82 and Best
// Practices 0.79. Static images, both pages score 1.00.

export type PreviewMode = 'screenshot'

export const PREVIEWS: Record<string, PreviewMode> = {
  'nera-agro.com': 'screenshot',
  'agropro.ag': 'screenshot',
  'kodaiverse.com': 'screenshot',
  'masushuaia.com': 'screenshot',
  'creativamedialab.com': 'screenshot',
  'telecentro.com.ar': 'screenshot',
}

/**
 * A host nobody declared still gets a screenshot, so a project added to `content.json`
 * without its PNG falls back to the striped placeholder rather than to nothing. The
 * unit test is what keeps it from staying undeclared.
 */
export function previewMode(host: string): PreviewMode {
  return PREVIEWS[host] ?? 'screenshot'
}

// Same host-keyed policy as `PREVIEWS`, for the rare project whose `content.json` URL is
// not what it should link to. `content.json` is read-only, so a mismatch is fixed here:
// `telecentro.com.ar` hardcodes the site root, but the product the owner built — and what
// the card's own description claims — is `/t-play`. Both the capture script's `goto` and
// the card's `href` resolve through `projectUrl`, so the two never drift apart.
export const URL_OVERRIDES: Record<string, string> = {
  'telecentro.com.ar': 'https://telecentro.com.ar/t-play',
}

export function projectUrl(host: string, fallback: string): string {
  return URL_OVERRIDES[host] ?? fallback
}

/**
 * Reveal stagger of the projects grid (`MOTION_SPEC` §9): 90ms per column, restarting
 * on every row, so a card is never held back by the rows above it. Three columns is the
 * widest the grid ever gets at `minmax(min(100%, 300px), 1fr)` inside `container-page`.
 */
export function projectDelay(index: number): number {
  return 90 * (index % 3)
}
